services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: magentoDB
      MYSQL_USER: magento
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
      - ./magentoDB:/docker-entrypoint-initdb.d

volumes:
  db_data: