services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - .:/var/www/html
  #   depends_on:
  #     - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: magentoDB
      MYSQL_USER: magento
      MYSQL_PASSWORD: 12345678
      MYSQL_PORT: 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./magentoDB:/docker-entrypoint-initdb.d
  
  php-fpm:
    build: 
      context: .
      dockerfile: dockerfile.php-fpm
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "4646:80"
    volumes:
      - .:/var/www/html
      - ./nginx_conf:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - db

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   ports:
  #     - "9201:9200"
  #     - "9301:9300"
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data

volumes:
  db_data: 
  # es_data:
