services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - .:/var/www/html
  #   depends_on:
  #     - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: magentoDB
      MYSQL_USER: magento
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
      - ./magentoDB:/docker-entrypoint-initdb.d
  
  php-fpm:
    build:
      context: .
      dockerfile: dockerfile.php-fpm
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "4646:80"
    volumes:
      - .:/var/www/html
      - ./nginx_conf:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - db

volumes:
  db_data: